# Generated by Django 3.1.4 on 2020-12-31 13:08

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20201230_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='notes.topic'),
        ),
    ]
