# Generated by Django 3.1.4 on 2020-12-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_topic_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
